server:
  port: 8090
  # 1核2G内存，线程数经验值200；4核8G内存【accept-count=1000、max-threads=800、max-connections=10000】，线程数经验值800。线程池过大，cpu调度会消耗大量时间
#  tomcat:
#    mbeanregistry:
#      enabled: true
#    max-connections: 100
#    threads:
#      max: 100        # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
#      min-spare: 50   # 初始化线程数,最小空闲线程数,默认是10
#    accept-count: 10  # 等待队列长度

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
#    # 访问频次限制
#    limit-count: 10
#    # 白名单，不做频次拦截【微信的openai】oxfA9w8-23yvwTmo2ombz0E4zJv4
#    white-list: ojbZUv18lbmriaTjcCWBYkOrSbHA
#    # 模型
#    model-types: glm-4,gpt-4,gpt-3.5-turbo
#    # 接口 appId、appToken - 调用 big-market 分配参数
#    big-market:
#      appId: chatgpt-data
#      appToken: 89iu7o8732ijd9114


# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 状态；true = 开启、false 关闭
      enabled: true
      # 官网地址 https://api.openai.com/ 1美金:7人民币。或者有ApiHost 这种代理地址和key，淘宝也可以
      api-host: https://pro-share-aws-api.zcyai.com/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: sk-SYVdsvPXaI6OUktu6e2bA87fD26348B5835f2aFc2374Cb17

# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_434fe75eafa0
    appid: wx5ee152cd94f078fc
    token: b8b6

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy
